name = "rcsb-api-worker"
account_id = "5cdde2791aa9609fed44884a0064c7bc"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "rcsb-db"
database_id = "738c9a5e-0c8a-4d7b-9eb9-95888ee6c8b7"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "rcsb-media"

[vars]
WORKER_SECRET = "RCSB_Admin_Secure_Key_2026"
R2_PUBLIC_URL = "https://media.rcsb.in"
SITE_URL = "https://rcsb-website.pages.dev"


[triggers]
crons = ["0 9 * * *"] # Runs every day at 9 AM

[[workflows]]
name = "event-reminder-workflow"
binding = "EVENT_REMINDER_WORKFLOW"
class_name = "EventReminderWorkflow"

[[workflows]]
name = "blog-announcement-workflow"
binding = "BLOG_ANNOUNCEMENT_WORKFLOW"
class_name = "BlogAnnouncementWorkflow"

[[workflows]]
name = "award-announcement-workflow"
binding = "AWARD_ANNOUNCEMENT_WORKFLOW"
class_name = "AwardAnnouncementWorkflow"

[[workflows]]
name = "project-announcement-workflow"
binding = "PROJECT_ANNOUNCEMENT_WORKFLOW"
class_name = "ProjectAnnouncementWorkflow"

